var products=[
{id:'solo-red',n:'一人食酸汤快乐锅',p:39.9,pt:'¥39.9',s:'red',r:'拉新款',sort:1,pri:6,sel:'单人小锅，低成本尝鲜。',feel:'我一个人试试，39.9 元不会有负担。',tags:['适合：一人食','升级点：轻量尝鲜','感知词：低门槛'],sc:'solo',bg:'linear-gradient(145deg,#ffd3b5,#b82722)',box:'#bc2e28',soup:'linear-gradient(145deg,#e14735,#831916)',items:['小锅','红酸汤','一人食'],photo:'assets/red-soup-detail.jpg',m:['价格轻，口味有代表性，适合先点进来看看。','花很少的钱就能尝到贵州红酸汤，不需要做复杂决策。','它不是追求丰盛，而是承担流量入口和首次尝鲜。','第一次接触巡黔记、一个人吃、想低成本试味的用户。',[92,72,42,62,22,76]]},
{id:'taste-red',n:'红酸汤尝鲜锅',p:158,pt:'¥158',s:'red',r:'主销款',sort:2,pri:1,sel:'牛肉、圈圈粉、蘸水到位。',feel:'这款看起来刚好适合我，不用想太多。',tags:['适合：2-4人','升级点：完整体验','感知词：不踩雷'],sc:'date',bg:'linear-gradient(145deg,#ffe0bd,#c7362c)',box:'#c5362c',soup:'linear-gradient(145deg,#d94131,#711715)',items:['牛肉','圈圈粉','蘸水'],photo:'assets/red-product.jpg',m:['这是最像标准答案的一款，价格和内容都比较稳。','红酸汤代表性强，配套完整，用户不用自己再补太多东西。','比一人食多了完整套装感，从试味变成一顿正式火锅。','情侣约会、首次购买、想买主流贵州味的人。',[82,88,72,66,36,90]]},
{id:'taste-white',n:'白酸汤尝鲜锅',p:158,pt:'¥158',s:'white',r:'新品复购',sort:3,pri:4,sel:'清爽鲜香，轻盈不厚重。',feel:'老口味吃过了，这个更清爽，想试试。',tags:['适合：老客尝鲜','升级点：清爽口味','感知词：新鲜'],sc:'repeat',bg:'linear-gradient(145deg,#fff8df,#e6bd69)',box:'#e4bc70',soup:'linear-gradient(145deg,#fff4c8,#d9b15b)',items:['白酸汤','鲜香','夏日感'],photo:'assets/white-hotpot-2.jpg',m:['同样 158，但口味更轻，像给老客的新选择。','不用离开价格舒适区，就能获得一条新风味体验。','贵点不在价格，而在巡黔记产品线的口味宽度。','吃过红酸汤、想换清爽口味、夏天购买的用户。',[80,78,58,90,30,74]]},
{id:'taste-bean',n:'豆米尝鲜锅',p:158,pt:'¥158',s:'bean',r:'暖锅款',sort:4,pri:5,sel:'绵密浓香，贵州家常味。',feel:'这个更暖、更饱，像家里会煮的一锅。',tags:['适合：秋冬暖胃','升级点：浓香饱腹','感知词：家常'],sc:'repeat',bg:'linear-gradient(145deg,#f4e7c0,#9eb06a)',box:'#9eaa65',soup:'linear-gradient(145deg,#c8c983,#83733d)',items:['豆米','浓香','暖胃'],photo:'assets/bean-hotpot-real.jpg',m:['它不像爆款口味，但很有贵州日常餐桌的记忆点。','豆米提供饱腹和暖感，适合从酸汤之外拓宽复购。','升级点在风味厚度和家常识别度。','老客复购、秋冬囤货、偏爱浓香口味的人。',[78,76,72,74,28,70]]},
{id:'party-188',n:'酸汤欢聚锅',p:188,pt:'¥188',s:'red',r:'聚会款',sort:5,pri:2,sel:'多人分享，配菜更丰盛。',feel:'多花一点，聚会更完整，也更省心。',tags:['适合：朋友小聚','升级点：配菜升级','感知词：丰盛'],sc:'friends',bg:'linear-gradient(145deg,#ffe0b7,#a9231f)',box:'#b92520',soup:'linear-gradient(145deg,#dc4332,#721613)',items:['多人','配菜','欢聚'],photo:'assets/red-set.jpg',m:['188 比 158 更像聚会一桌，不只是尝鲜。','配菜和分享感更强，用户能把它和朋友小聚直接关联。','从完整体验升级到多人分享，丰盛感明显更高。','朋友小聚、家庭周末、想省心搭配的人。',[76,88,84,62,34,86]]},
{id:'meat-238',n:'大口吃肉锅',p:238,pt:'¥238',s:'red',r:'利润款',sort:6,pri:3,sel:'肉量更足，满足感更强。',feel:'虽然贵一点，但肉量看得见，值感更直接。',tags:['适合：肉食爱好者','升级点：肉量升级','感知词：满足'],sc:'meat',bg:'linear-gradient(145deg,#ffd0ad,#8f1b18)',box:'#9e201d',soup:'linear-gradient(145deg,#d83d2f,#651211)',items:['牛肉+','厚切','满足'],photo:'assets/ingredients-set.jpg',m:['贵得有理由，因为肉量差异第一眼能看到。','用户不需要理解复杂卖点，肉多就是最直接的值。','比 188 更强调主菜和满足感，利润空间也更清晰。','肉食爱好者、男生聚餐、对分量敏感的人。',[70,82,92,58,30,82]]},
{id:'cp-248',n:'红白酸汤CP锅',p:248,pt:'¥248',s:'white',r:'双拼款',sort:7,pri:7,sel:'红白双汤底，一次双体验。',feel:'有选择感，也有新鲜感，适合两个人点。',tags:['适合：双人尝鲜','升级点：双汤底','感知词：新鲜'],sc:'date',bg:'linear-gradient(145deg,#fff4d8 0%,#e5bc68 48%,#bd2c27 100%)',box:'#d5a458',soup:'linear-gradient(90deg,#d83d2e 0 50%,#fff1bd 50% 100%)',items:['红汤','白汤','双拼'],photo:'assets/white-hotpot-1.jpg',m:['它像一个有趣的双拼方案，不只是加价。','一次解决两种口味偏好，降低一起吃饭时的选择冲突。','比单汤底多了对比体验和社交话题感。','情侣约会、双人尝鲜、想试新品但又怕踩雷的人。',[68,84,78,92,38,78]]},
{id:'party-399',n:'派对之王party锅',p:399,pt:'¥399',s:'red',r:'派对款',sort:8,pri:8,sel:'电煮锅到位，开箱即开吃。',feel:'这不是一份菜，是团建露营解决方案。',tags:['适合：团建露营','升级点：电煮锅','感知词：省心'],sc:'camp',bg:'linear-gradient(145deg,#ffd6a7,#72301c)',box:'#7b3520',soup:'linear-gradient(145deg,#d63c2f,#6c1514)',items:['电煮锅','露营','派对'],photo:'assets/party-box.png',m:['价格高，但场景很明确，像一套活动方案。','电煮锅和整套搭配减少准备成本，让高价变得合理。','从商品升级为场景解决方案，承担团建和露营任务。','团建、露营、多人派对、想省心组织饭局的人。',[54,94,90,76,62,80]]},
{id:'gift-599',n:'贵州家宴至尊锅',p:599,pt:'¥599',s:'red',r:'礼赠款',sort:9,pri:9,sel:'高端礼盒，家宴与商务都体面。',feel:'贵，但它买的是体面、完整和品牌高度。',tags:['适合：商务送礼','升级点：高端礼盒','感知词：体面'],sc:'gift',bg:'linear-gradient(145deg,#ffe2a9,#841917)',box:'#8a1816',soup:'linear-gradient(145deg,#da3d31,#651211)',items:['礼盒','家宴','至尊'],photo:'assets/supreme-box.png',m:['这不是日常买菜价格，而是礼赠和品牌形象款。','高端礼盒、完整家宴和贵州原产地品牌背书共同支撑价格。','比 399 更强调礼赠体面和品牌高度，而非单纯分量。','商务送礼、年节家宴、需要体面表达贵州味的人。',[42,86,94,70,98,72]]}
];
var scenarios=[['solo','低成本尝鲜','一个人吃，低成本尝鲜','solo-red','我一个人试试，39.9 元不会有负担。'],['date','双人特别一点','两个人约会，吃点特别的','taste-red','这款看起来刚好适合我，不用想太多。'],['friends','丰盛省心','朋友小聚，丰盛又省心','party-188','多花一点，聚会更完整，也更省心。'],['meat','肉量满足','肉食爱好者，想吃得更满足','meat-238','虽然贵一点，但肉量看得见，值感更直接。'],['repeat','老客尝鲜','老客复购，试试新口味','taste-white','老口味吃过了，这个更清爽，想试试。'],['camp','一套搞定','团建露营，一套搞定','party-399','这不是一份菜，是团建露营解决方案。'],['gift','体面高级','商务送礼，体面高级','gift-599','贵，但它买的是体面、完整和品牌高度。']];
var labels=['价格接受度','场景匹配度','丰盛感','新鲜感','礼赠体面感','下单信心'],KEY='xunqianji_v2_ab_stats',SESSION_KEY='xunqianji_v2_session_id',mode='A',selected='solo',filter=null,active=null;
var SUPABASE_REST_URL='https://ioxmcmootxxenmbmnruo.supabase.co/rest/v1',SUPABASE_TABLE='click_events',SUPABASE_PUBLIC_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlveG1jbW9vdHh4ZW5tYm1ucnVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODI0NDQzODgsImV4cCI6MjA5ODAyMDM4OH0.10W4H8QdguRd7qQouKi0f5j9g8ji_JcAuRlAUAzb96U';
var $=function(q){return document.querySelector(q)}, $$=function(q){return Array.prototype.slice.call(document.querySelectorAll(q))}, byId=function(id){return products.find(function(p){return p.id===id})};
function sessionId(){var id=localStorage.getItem(SESSION_KEY);if(!id){id='s_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,10);localStorage.setItem(SESSION_KEY,id)}return id}
function cloudTrack(action,data){if(!window.fetch||!SUPABASE_PUBLIC_KEY)return;data=data||{};var p=data.sku_id?byId(data.sku_id):null;var payload={session_id:sessionId(),ab_version:mode,scenario_id:selected,sku_id:data.sku_id||'',action:action,price:data.price!=null?data.price:(p?p.p:null),feedback:data.feedback||'',page_url:location.href,user_agent:navigator.userAgent};fetch(SUPABASE_REST_URL+'/'+SUPABASE_TABLE,{method:'POST',headers:{apikey:SUPABASE_PUBLIC_KEY,Authorization:'Bearer '+SUPABASE_PUBLIC_KEY,'Content-Type':'application/json',Prefer:'return=minimal'},body:JSON.stringify(payload)}).catch(function(err){console.warn('cloud stats failed',err)})}
function stats(){try{return JSON.parse(localStorage.getItem(KEY)||'{"modeViews":{"A":0,"B":0},"products":{}}')}catch(e){return {modeViews:{A:0,B:0},products:{}}}}
function save(s){localStorage.setItem(KEY,JSON.stringify(s))}
function count(id,key){var s=stats();s.products[id]=s.products[id]||{views:0,clicks:0,expensive:0,confused:0};s.products[id][key]=(s.products[id][key]||0)+1;save(s);cloudTrack(key,{sku_id:id,feedback:key});results()}
function visual(p){var photo=p.photo?'<img class="realPhoto" src="'+p.photo+'" alt="'+p.n+'">':'';return '<div class="visual '+(p.photo?'hasPhoto':'')+'" style="--bg:'+p.bg+';--box:'+p.box+';--soup:'+p.soup+'">'+photo+'<span class="badge">'+p.r+'</span><span class="price">'+p.pt+'</span><div class="scene"><div class="box"></div><div class="vpot"><div class="vsoup"><i></i><i></i><i></i><em></em></div></div><span class="meatSlice m1"></span><span class="meatSlice m2"></span><span class="noodle"></span><span class="ing i1">'+p.items[0]+'</span><span class="ing i2">'+p.items[1]+'</span><span class="ing i3">'+p.items[2]+'</span><span class="ing i4">'+(p.p>=399?'方案感':'贵州味')+'</span></div></div>'}
function card(p,featured){return '<article class="product '+(featured?'featured ':'')+'" data-card="'+p.id+'">'+visual(p)+'<div class="info"><div class="meta"><strong class="money">'+p.pt+'</strong><span class="role">'+p.r+'</span></div><h3>'+p.n+'</h3><p class="line">'+p.sel+'</p><p class="feel">'+p.feel+'</p><div class="ptags">'+p.tags.map(function(t){return '<span>'+t+'</span>'}).join('')+'</div><button class="cta" data-product="'+p.id+'">查看点击感知</button></div></article>'}
function compact(p){return '<div class="product hot">'+visual(p)+'<div class="info"><div class="meta"><strong class="money">'+p.pt+'</strong><span class="role">'+p.r+'</span></div><h3>'+p.n+'</h3><p class="line">'+p.sel+'</p><p class="feel">'+p.feel+'</p><button class="cta" data-product="'+p.id+'">查看点击感知</button></div></div>'}
function renderScenes(){$('#scenarioList').innerHTML=scenarios.map(function(s){return '<button class="scenarioCard '+(s[0]===selected?'active':'')+'" data-scenario="'+s[0]+'"><span>'+s[1]+'</span><strong>'+s[2]+'</strong></button>'}).join('')}
function scenePanel(){var sc=scenarios.find(function(s){return s[0]===selected}),p=byId(sc[3]);$('#sceneMind').textContent=sc[4];$('#sceneProduct').innerHTML=compact(p);highlight(p.id)}
function renderProducts(){var list=products.slice();if(filter)list=list.filter(function(p){return p.s===filter});if(mode==='A'){list.sort(function(a,b){return a.sort-b.sort});$('#matrixTitle').textContent=filter?'A版：筛选后的价格带货架':'A版：按价格带形成清晰升级货架';$('#flow').textContent='39.9 → 158 → 188 → 238 → 248 → 399 → 599'}else{list.sort(function(a,b){return a.pri-b.pri});$('#matrixTitle').textContent=filter?'B版：筛选后的场景优先推荐':'B版：按用户场景组织主推与备选';$('#flow').textContent='先看场景 → 再看产品 → 最后理解价格'}$('#productGrid').innerHTML=list.map(function(p,i){return card(p,mode==='B'&&i===0)}).join('');var sc=scenarios.find(function(s){return s[0]===selected});highlight(sc&&sc[3])}
function setMode(m){mode=m;cloudTrack('mode_switch',{feedback:m});var st=stats();st.modeViews=st.modeViews||{A:0,B:0};st.modeViews[m]=(st.modeViews[m]||0)+1;save(st);$$('[data-mode]').forEach(function(el){el.classList.toggle('active',el.dataset.mode===m)});$('#productGrid').classList.add('changing');setTimeout(function(){renderProducts();$('#productGrid').classList.remove('changing');results()},160)}
function highlight(id){$$('[data-card]').forEach(function(c){c.classList.toggle('hot',c.dataset.card===id)})}
function openModal(id){active=byId(id);if(!active)return;count(id,'views');$('#mRole').textContent=active.r;$('#mTitle').textContent=active.n+' · '+active.pt;$('#mReaction').textContent=active.m[0];$('#mValue').textContent=active.m[1];$('#mUpgrade').textContent=active.m[2];$('#mAudience').textContent=active.m[3];$('#scores').innerHTML=labels.map(function(l,i){var v=active.m[4][i];return '<div class="score"><span>'+l+'</span><div class="track"><div class="fill" style="width:'+v+'%"></div></div><b>'+v+'</b></div>'}).join('');$('#modal').classList.add('open');$('#modal').setAttribute('aria-hidden','false')}
function closeModal(){$('#modal').classList.remove('open');$('#modal').setAttribute('aria-hidden','true')}
function results(){var s=stats();function top(k){var best=null;products.forEach(function(p){var v=((s.products||{})[p.id]||{})[k]||0;if(!best||v>best.v)best={p:p,v:v}});return best&&best.v>0?best.p.n+'（'+best.v+'）':'暂无数据'}$('#topClick').textContent=top('clicks');$('#topView').textContent=top('views');$('#topConfused').textContent=top('confused');$('#modeResult').textContent=mode==='A'?'A版更适合展示价格梯度':'B版更适合降低选择困难'}
document.addEventListener('click',function(e){var m=e.target.closest('[data-mode]'),sc=e.target.closest('[data-scenario]'),prod=e.target.closest('[data-product]'),close=e.target.closest('[data-close]'),fb=e.target.closest('[data-feedback]'),ser=e.target.closest('.seriesCard');if(m)setMode(m.dataset.mode);if(sc){selected=sc.dataset.scenario;cloudTrack('scenario_select',{feedback:selected});renderScenes();scenePanel()}if(prod)openModal(prod.dataset.product);if(close)closeModal();if(fb&&active){count(active.id,fb.dataset.feedback==='click'?'clicks':fb.dataset.feedback);closeModal()}if(ser){filter=filter===ser.dataset.series?null:ser.dataset.series;cloudTrack('series_filter',{feedback:filter||'all'});$$('.seriesCard').forEach(function(c){c.classList.toggle('selected',filter===c.dataset.series)});renderProducts();$('#products').scrollIntoView({behavior:'smooth'})}});
document.addEventListener('keydown',function(e){if(e.key==='Escape')closeModal()});
var obs=new IntersectionObserver(function(es){es.forEach(function(en){if(en.isIntersecting)en.target.classList.add('show')})},{threshold:.15});$$('.reveal').forEach(function(el){obs.observe(el)});
var navObs=new IntersectionObserver(function(es){es.forEach(function(en){if(en.isIntersecting)$$('#navLinks a').forEach(function(a){a.classList.toggle('active',a.getAttribute('href')==='#'+en.target.id)})})},{rootMargin:'-35% 0px -55% 0px'});$$('main section[id]').forEach(function(s){navObs.observe(s)});
renderScenes();renderProducts();scenePanel();setMode('A');results();